### ISSUE TITLE
请教下

### ISSUE THREAD

**Issue by rilyuuj** [thawk/wiki#2]
目前正在寻找MSYS2下的dig解决方案，官方源貌似没有bindutil的包，up主是怎么解决的呢？

**Comment by thawk** [comment]
dig?好像没用过呢。我目前主力在MacOS和ArchLinux环境。MSYS2、Cygwin、WSL都不太好用，只是偶尔用一下而已

**Comment by rilyuuj** [comment]
好吧，还是纯Linux环境好。感谢回复
